# Generated by Django 4.0.4 on 2022-05-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField()),
                ('final_efficiency', models.FloatField(null=True)),
                ('final_distribution_efficiency', models.FloatField(null=True)),
                ('final_quality', models.FloatField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operation_id', models.UUIDField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField()),
                ('efficiency', models.FloatField(null=True)),
                ('distribution_efficiency', models.FloatField(null=True)),
                ('quality', models.FloatField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_control.session')),
            ],
        ),
    ]
